[BugFix][v0.26.0rc] Fix MegaMoe hang when main and draft models have inconsistent MoE quantization (#14747)
### What this PR does / why we need it?
If the quantization modes of the main model and draft model are
inconsistent, for example, the main model is a quantized model and the
draft model is a floating-point model, the MEGAMOE operator reports an
error, indicating that this format is not supported.
The error message is as follows:
```
RuntimeError: call aclnnMegaMoe failed, detail:[PID: 2799] 2026-08-20-22:15:59.473.813 Execution_Error(EZ1008): Failed to execute operator MegaMoe_6081. Reason: Failed to execute tiling function.
        Solution: 1.If the tiling function does not exist, check whether the tiling function is registered successfully. 2.If the tiling function fails to be executed, check the implementation logic of the tiling function.
TraceBack (most recent call last):
        weight1[0] must be 2-dimension, but got 3 dim.[FUNC:CheckWeight1Input][FILE:mega_moe_tiling_arch22.cpp][LINE:648]
        CheckWeight1Input failed.[FUNC:MegaMoeA2A3CheckShapeAndSetTiling][FILE:mega_moe_tiling_arch22.cpp][LINE:860]
        MegaMoeA2A3 CheckShapeAndSetTiling Failed[FUNC:MegaMoeA2A3TilingFuncImpl][FILE:mega_moe_tiling_arch22.cpp][LINE:1139]
        Failed to execute operator MegaMoe_6081. Reason: Failed to execute tiling function.
        Check NnopbaseExecutorDoTiling(executor) failed
        Check NnopbaseExecutorTilingAndUpdateBinInfo(executor) failed
        Check NnopbaseExecutorMatchCache(executor) failed
        Check NnopbaseRunForWorkspace(*executor, workspaceSize) failed
```

**Modification plan:**
When it is identified that the current weight is in this hybrid format,
the draft model will be rolled back to the small operator path.

This PR is only a workaround for version 0.26.0rc. The main branch will
address this issue through the megamoe operator.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
nightly test case: `glm-4.7-w8a8`


- vLLM version: v0.26.0
- vLLM main:
https://github.com/vllm-project/vllm/commit/d02df748bf9efd99022f1a062597dc3cb3808485

Signed-off-by: wangkunpeng <1289706727@qq.com>